---
auth:
  guest: guest

global:
  port: 5704
  data_dir: ./data
  receiver_timeout: 10
  rebalance_interval: 5
  prune_interval: 3600
  partitions: 1
  ttl: 2592000 # 30 days
  
streams:
  test:
    partitions: 4
